version: '3'

services:
  httpd:
    container_name: "${PROJECT_NAME}_httpd_1"
    image: httpd:2.4.25
    restart: always
    environment:
      - APACHE_LOG_DIR=/usr/local/apache2/logs
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ${DOCKER_STACK_DIR}/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ${DOCKER_STACK_DIR}/httpd/vhosts/:/usr/local/apache2/conf/vhosts
      - ${ROOT_DIR}/www:/var/www
    links:
      - php
    depends_on:
      - php
  php:
    container_name: "${PROJECT_NAME}_php_1"
    build: ${DOCKER_STACK_DIR}/php
    restart: always
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - ${ROOT_DIR}/www:/var/www
    environment:
      HTTP_PORT: "${HTTP_PORT}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    depends_on:
      - db
    links:
      - db
  db:
    container_name: "${PROJECT_NAME}_mysql_1"
    restart: always
    image: mysql:5.5
    volumes:
      - ${DOCKER_STACK_DIR}/mysql:/etc/mysql/conf.d
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  phpmyadmin:
    container_name: "${PROJECT_NAME}_phpmyadmin_1"
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "${PHPMYADMIN_PORT}:80"
    links:
      - db
    depends_on:
      - db
volumes:
  dbdata: